languageCode: en
languageName: English
displayName: EN


title: '[root&#64;emanuelmairoll.at]#'
description: Some description
copyright: © 2023 Emanuel J. Mairoll


author:
  name: Emanuel Mairoll
  image: le_me.jpg
  headline: Software Dev // Tinkerer // God of Chaos
  bio: Software Developer
  links:
    - github: 'https://github.com/EmanuelMairoll'
    - stack-overflow: 'https://stackoverflow.com/users/18277713/emanuelm'
    - linkedin: 'https://www.linkedin.com/in/emanuel-mairoll-512458164/'
    - envelope: 'mailto:sigmoid_flavors_0u@icloud.com'
