main:
  - name: Blog
    pageRef: blog
    weight: 10
  - name: Résumé
    pageRef: resume
    weight: 20
  - name: Experience
    pageRef: experience
    weight: 30
  - name: About Me
    pageRef: aboutme
    weight: 40
  - pre: github
    url: 'https://github.com/EmanuelMairoll'
    weight: 50
footer:
  - name: Acknowledgements
    pageRef: acknowledgements
    weight: 10
  - name: Privacy
    pageRef: privacy
    weight: 20
