colorScheme: ocean
defaultAppearance: dark
autoSwitchAppearance: false

header:
  layout: fixed

footer:
  showThemeAttribution: false
  showAppearanceSwitcher: true
  showMenu: true
  showCopyright: true
  showScrollToTop: false

homepage:
  layout: background
  homepageImage: background.jpg